filter:
    excluded_paths:
        - "tests/"               # Everything in a root level "tests" directory
        - "vendor/"                # Without trailing "/", just ignores a single file name "tests"

build:
    environment:
        php:
            version: 7.1
            version: 5.6
    tests:
        override:
            -
                command: 'vendor/bin/phpspec run'