filter:
    excluded_paths:
        - "tests/"               # Everything in a root level "tests" directory
        - "vendor/"                # Without trailing "/", just ignores a single file name "tests"

build:
    nodes:
        php55:
            environment:
                php: 5.5
        tests:
            override:
                -
                    command: 'vendor/bin/phpspec run'
        php56:
            environment:
                php: 5.6
        tests:
            override:
                -
                    command: 'vendor/bin/phpspec run'
        php70:
            environment:
                php: 7.0
        tests:
            override:
                -
                    command: 'vendor/bin/phpspec run'
        php71:
            environment:
                php: 7.1
        tests:
            override:
                -
                    command: 'vendor/bin/phpspec run'

