filter:
    excluded_paths:
        - "tests/"               # Everything in a root level "tests" directory
        - "vendor/"                # Without trailing "/", just ignores a single file name "tests"

build:
    environment:
        php: 5.5
        php: 5.6
        php: 7.0
        php: 7.1 

    tests:
        override:
            -
                command: 'vendor/bin/phpspec run'