language: php

stage: "Tests without hitting api endpoints"

php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - alfred_workflow_data=./tests/mo.com.sleeplessmind.time
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --group=default --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

jobs:
  include:
    - stage: "Tests not hitting api endpoints"
      php: 7.1
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS="--prefer-lowest"
    - stage: "Tests hitting api endpoints"
      name: "Tests hitting api endpoints - php72 prefer-lowest"
      php: 7.2
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS="--prefer-lowest"
    - stage: "Tests hitting api endpoints"
      name: "Tests hitting api endpoints - php73 prefer-lowest"
      php: 7.3
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS="--prefer-lowest"
    - stage: "Tests hitting api endpoints"
      name: "Tests hitting api endpoints - php71"
      php: 7.1
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS=""
    - stage: "Tests hitting api endpoints"
      name: "Tests hitting api endpoints - php72"
      php: 7.2
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS=""
    - stage: "Tests hitting api endpoints"
      name: "Tests hitting api endpoints - php73"
      php: 7.3
      script: vendor/bin/phpunit --group=timerServicesApiCalls --coverage-text --coverage-clover=coverage.clover
      env: COMPOSER_FLAGS=""
